bsz: 512
clamp_len: -1
clip_value: 10
cuda: true
d_ff: 512
d_model: 128
data_root: ../datasets
data_source: joshi
debug: false
deterministic: false
dropout_rate: 0.1
exp_dir: logs/tsp50_seg25_exp2
gpu_id: '7'
internal_drop: 0.1
learning_rate: 0.0001
log_interval: 500
loss_fn: reinforce
multi_gpu: false
n_dec_layer: 2
n_enc_layer: 6
n_epoch: 10000
n_head: 8
n_point: 50
optim: adam
pre_lnorm: true
rl: true
rl_eval_maxstep: 20
rl_maxstep: 2500
seed: 1234
segm_len: 25
sorted: false
tol: 0.001
restart: -1
reset_log: false